import { PrismaClient, BadgeCategory, BadgeRarity } from "@prisma/client"

const prisma = new PrismaClient()

const badges = [
  // MILESTONE badges
  {
    name: "bem_vindo",
    slug: "bem-vindo",
    description: "Bem-vindo à nossa comunidade! Obrigado por se juntar a nós.",
    icon: "👋",
    category: BadgeCategory.MILESTONE,
    rarity: BadgeRarity.COMMON,
    criteriaType: "user_registration",
    criteriaValue: 1,
    pointsReward: 10,
    isActive: true,
    isSecret: false,
  },
  {
    name: "primeira_semana",
    slug: "primeira-semana",
    description: "Usou a plataforma por uma semana completa!",
    icon: "📅",
    category: BadgeCategory.MILESTONE,
    rarity: BadgeRarity.COMMON,
    criteriaType: "days_active",
    criteriaValue: 7,
    pointsReward: 25,
    isActive: true,
    isSecret: false,
  },
  {
    name: "veterano",
    slug: "veterano",
    description: "Membro ativo há 30 dias. Sua dedicação é inspiradora!",
    icon: "🎖️",
    category: BadgeCategory.MILESTONE,
    rarity: BadgeRarity.UNCOMMON,
    criteriaType: "days_active",
    criteriaValue: 30,
    pointsReward: 50,
    isActive: true,
    isSecret: false,
  },

  // COMMUNITY badges
  {
    name: "primeiro_post",
    slug: "primeiro-post",
    description: "Publicou sua primeira postagem na comunidade!",
    icon: "📝",
    category: BadgeCategory.COMMUNITY,
    rarity: BadgeRarity.COMMON,
    criteriaType: "posts_created",
    criteriaValue: 1,
    pointsReward: 10,
    isActive: true,
    isSecret: false,
  },
  {
    name: "contador_historias",
    slug: "contador-historias",
    description: "Compartilhou 10 histórias com a comunidade.",
    icon: "📚",
    category: BadgeCategory.COMMUNITY,
    rarity: BadgeRarity.UNCOMMON,
    criteriaType: "posts_created",
    criteriaValue: 10,
    pointsReward: 30,
    isActive: true,
    isSecret: false,
  },
  {
    name: "influenciador",
    slug: "influenciador",
    description: "Criou 50 postagens inspiradoras na comunidade.",
    icon: "👑",
    category: BadgeCategory.COMMUNITY,
    rarity: BadgeRarity.RARE,
    criteriaType: "posts_created",
    criteriaValue: 50,
    pointsReward: 100,
    isActive: true,
    isSecret: false,
  },
  {
    name: "participativo",
    slug: "participativo",
    description: "Contribuiu com 50 comentários valiosos.",
    icon: "💬",
    category: BadgeCategory.COMMUNITY,
    rarity: BadgeRarity.UNCOMMON,
    criteriaType: "comments_created",
    criteriaValue: 50,
    pointsReward: 25,
    isActive: true,
    isSecret: false,
  },
  {
    name: "popular",
    slug: "popular",
    description: "Recebeu 100 upvotes em suas contribuições.",
    icon: "⭐",
    category: BadgeCategory.COMMUNITY,
    rarity: BadgeRarity.RARE,
    criteriaType: "upvotes_received",
    criteriaValue: 100,
    pointsReward: 75,
    isActive: true,
    isSecret: false,
  },

  // SESSIONS badges
  {
    name: "primeira_sessao",
    slug: "primeira-sessao",
    description: "Participou da sua primeira sessão em grupo!",
    icon: "🎯",
    category: BadgeCategory.SESSIONS,
    rarity: BadgeRarity.COMMON,
    criteriaType: "sessions_attended",
    criteriaValue: 1,
    pointsReward: 15,
    isActive: true,
    isSecret: false,
  },
  {
    name: "assiduo",
    slug: "assiduo",
    description: "Participou de 10 sessões. Sua presença é constante!",
    icon: "📅",
    category: BadgeCategory.SESSIONS,
    rarity: BadgeRarity.UNCOMMON,
    criteriaType: "sessions_attended",
    criteriaValue: 10,
    pointsReward: 50,
    isActive: true,
    isSecret: false,
  },
  {
    name: "comprometido",
    slug: "comprometido",
    description: "Participou de 50 sessões. Seu compromisso é excepcional!",
    icon: "🏆",
    category: BadgeCategory.SESSIONS,
    rarity: BadgeRarity.EPIC,
    criteriaType: "sessions_attended",
    criteriaValue: 50,
    pointsReward: 200,
    isActive: true,
    isSecret: false,
  },

  // WELLNESS badges
  {
    name: "autoconhecimento",
    slug: "autoconhecimento",
    description: "Começou sua jornada de autocuidado registrando seu primeiro humor.",
    icon: "😊",
    category: BadgeCategory.WELLNESS,
    rarity: BadgeRarity.COMMON,
    criteriaType: "mood_entries",
    criteriaValue: 1,
    pointsReward: 10,
    isActive: true,
    isSecret: false,
  },
  {
    name: "semana_consistente",
    slug: "semana-consistente",
    description: "Registrou seu humor por 7 dias consecutivos!",
    icon: "🔥",
    category: BadgeCategory.WELLNESS,
    rarity: BadgeRarity.UNCOMMON,
    criteriaType: "mood_streak",
    criteriaValue: 7,
    pointsReward: 30,
    isActive: true,
    isSecret: false,
  },
  {
    name: "mes_consciencia",
    slug: "mes-consciencia",
    description: "Manteve uma sequência de 30 dias registrando seu humor.",
    icon: "🌙",
    category: BadgeCategory.WELLNESS,
    rarity: BadgeRarity.RARE,
    criteriaType: "mood_streak",
    criteriaValue: 30,
    pointsReward: 100,
    isActive: true,
    isSecret: false,
  },
  {
    name: "mestre_streak",
    slug: "mestre-streak",
    description: "Atingiu uma sequência impressionante de 100 dias!",
    icon: "👑",
    category: BadgeCategory.WELLNESS,
    rarity: BadgeRarity.LEGENDARY,
    criteriaType: "mood_streak",
    criteriaValue: 100,
    pointsReward: 500,
    isActive: true,
    isSecret: true,
  },
  {
    name: "reflexivo",
    slug: "reflexivo",
    description: "Escreveu 10 entradas profundas no diário.",
    icon: "✍️",
    category: BadgeCategory.WELLNESS,
    rarity: BadgeRarity.UNCOMMON,
    criteriaType: "journal_entries",
    criteriaValue: 10,
    pointsReward: 25,
    isActive: true,
    isSecret: false,
  },
  {
    name: "escritor_prolifico",
    slug: "escritor-prolifico",
    description: "Produziu 50 entradas no diário. Sua escrita é inspiradora!",
    icon: "📖",
    category: BadgeCategory.WELLNESS,
    rarity: BadgeRarity.RARE,
    criteriaType: "journal_entries",
    criteriaValue: 50,
    pointsReward: 75,
    isActive: true,
    isSecret: false,
  },
  {
    name: "mestre_zen",
    slug: "mestre-zen",
    description: "Completou 30 exercícios de mindfulness. Paz interior alcançada!",
    icon: "🧘‍♀️",
    category: BadgeCategory.WELLNESS,
    rarity: BadgeRarity.RARE,
    criteriaType: "exercises_completed",
    criteriaValue: 30,
    pointsReward: 80,
    isActive: true,
    isSecret: false,
  },
  {
    name: "guerreiro_respiracao",
    slug: "guerreiro-respiracao",
    description: "Praticou 20 exercícios de respiração. Mestre da respiração!",
    icon: "💨",
    category: BadgeCategory.WELLNESS,
    rarity: BadgeRarity.UNCOMMON,
    criteriaType: "breathing_exercises",
    criteriaValue: 20,
    pointsReward: 40,
    isActive: true,
    isSecret: false,
  },

  // SOCIAL badges
  {
    name: "acolhedor",
    slug: "acolhedor",
    description: "Deixou 10 comentários acolhedores em posts de novos membros.",
    icon: "🤗",
    category: BadgeCategory.SOCIAL,
    rarity: BadgeRarity.UNCOMMON,
    criteriaType: "helpful_comments",
    criteriaValue: 10,
    pointsReward: 25,
    isActive: true,
    isSecret: false,
  },
  {
    name: "mentor_comunidade",
    slug: "mentor-comunidade",
    description: "Forneceu 20 respostas úteis, ajudando outros membros.",
    icon: "🎓",
    category: BadgeCategory.SOCIAL,
    rarity: BadgeRarity.RARE,
    criteriaType: "helpful_responses",
    criteriaValue: 20,
    pointsReward: 60,
    isActive: true,
    isSecret: false,
  },

  // SPECIAL badges
  {
    name: "early_adopter",
    slug: "early-adopter",
    description: "Um dos primeiros membros da nossa comunidade. Pioneiro!",
    icon: "🚀",
    category: BadgeCategory.SPECIAL,
    rarity: BadgeRarity.EPIC,
    criteriaType: "user_creation_date",
    criteriaValue: 1,
    criteriaExtra: JSON.stringify({ before: "2024-12-01" }),
    pointsReward: 150,
    isActive: true,
    isSecret: true,
  },

  // Additional badges for completeness
  {
    name: "primeiro_comentario",
    slug: "primeiro-comentario",
    description: "Deixou seu primeiro comentário na comunidade!",
    icon: "💭",
    category: BadgeCategory.COMMUNITY,
    rarity: BadgeRarity.COMMON,
    criteriaType: "comments_created",
    criteriaValue: 1,
    pointsReward: 5,
    isActive: true,
    isSecret: false,
  },
  {
    name: "primeiro_exercicio",
    slug: "primeiro-exercicio",
    description: "Completou seu primeiro exercício de mindfulness!",
    icon: "🌱",
    category: BadgeCategory.WELLNESS,
    rarity: BadgeRarity.COMMON,
    criteriaType: "exercises_completed",
    criteriaValue: 1,
    pointsReward: 15,
    isActive: true,
    isSecret: false,
  },
  {
    name: "primeira_semana_streak",
    slug: "primeira-semana-streak",
    description: "Manteve uma sequência de 7 dias fazendo check-in diário!",
    icon: "⚡",
    category: BadgeCategory.MILESTONE,
    rarity: BadgeRarity.UNCOMMON,
    criteriaType: "daily_checkins",
    criteriaValue: 7,
    pointsReward: 35,
    isActive: true,
    isSecret: false,
  },
]

export async function seedBadges() {
  console.log("Seeding wellness badges...")

  for (const badge of badges) {
    await prisma.badge.upsert({
      where: { name: badge.name },
      update: badge,
      create: badge,
    })
  }

  console.log(`Seeded ${badges.length} wellness badges`)
}